### ISSUE TITLE
crash when share to facebook without install facebook app

### ISSUE THREAD

**Issue by bearprada** [bearprada/good-thing-map-android#3]
crash log

```
com.facebook.FacebookException: Unable to create Intent; this likely means the Facebook app is not installed.
            at com.facebook.widget.FacebookDialog$Builder.build(FacebookDialog.java:594)
            at goodthingmap.android.prada.lab.goodthingmap.DetailActivity$PlaceholderFragment.shareToFacebook(DetailActivity.java:335)
            at goodthingmap.android.prada.lab.goodthingmap.DetailActivity$PlaceholderFragment.onClick(DetailActivity.java:474)
            at android.view.View.performClick(View.java:4204)
            at android.view.View$PerformClick.run(View.java:17355)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by bearprada** [comment]
Implemented in PR #29: https://github.com/bearprada/good-thing-map-android/pull/29

The fix guards Facebook availability and catches `FacebookException` from the SDK launch path, routing to the install fallback dialog. Two Android 17 regression tests pass, including the no-Facebook path and an SDK-launch failure path. The issue remains open until the PR is reviewed and merged.
